### ISSUE TITLE
Improve image grids and galleries

### ISSUE THREAD

**Issue by GBergatto** [Team-Isaac-Polito/isaac-website#224]
The images in the grid in the Events page and galleries/carousels are too small and far apart from each other.

**Comment by cristinagenduso** [comment]
Since these are only placeholders, I will wait until we have the final images to avoid unnecessary duplication of effort. A similar issue was previously addressed (see issue #211), which was closed after making some changes to the code. As the images will vary in shape and size, they will need to be handled on a case-by-case basis. Therefore, this issue will be closed once we have all the photos and can adjust the dimensions accordingly.
